# Sử dụng Node.js phiên bản 14 làm base image
FROM node:14

# Tạo thư mục làm việc cho ứng dụng
WORKDIR /usr/src/app

# Copy package.json và package-lock.json (nếu có)
COPY package*.json ./

# Cài đặt các dependencies
RUN npm install

# Copy toàn bộ mã nguồn của bạn vào container
COPY . .

# Lắng nghe trên cổng 3000
EXPOSE 3000

# Chạy ứng dụng
CMD [ "node", "index.js" ]
